version: "3.8"
services:
  localstack:
    image: localstack/localstack:1.4
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=kms,s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack
    volumes:
      - ./localstack:/tmp/localstack
